
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-url-shortener
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      KAFKA_BROKER: kafka:9092   # This is correct
      KAFKA_TOPIC: url-shortening
    depends_on:
      - redis1
      - redis2
      - kafka
    command: ["wait-for-it", "kafka:9092", "--", "python", "app.py"]  # Ensure Kafka is up before starting the app
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512MB

  redis1:
    image: redis:6
    container_name: redis-primary
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          memory: 500MB
        reservations:
          memory: 256MB

  redis2:
    image: redis:6
    container_name: redis-secondary
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          memory: 500MB
        reservations:
          memory: 256MB

  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512MB

  zookeeper:
    image: bitnami/zookeeper:3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    deploy:
      resources:
        limits:
          memory: 500MB
        reservations:
          memory: 256MB
