version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-url-shortener
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.bigshort.one`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api-secure.rule=Host(`api.bigshort.one`)"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      KAFKA_BROKER: kafka-1:9092
      KAFKA_TOPIC: url_shortening_topic
      REDIS_URL: redis-urls
      REDIS_PC: redis-pc
      DB_HOST: postgres-1
    networks:
      - proxy
    extra_hosts:  
      - "redis-urls:host-gateway"
      - "redis-pc:host-gateway"
      - kafka-1:host-gateway
      - postgres-1:host-gateway
networks:
  proxy:
    external: true