version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-url-shortener
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: url_shortening_topic
    depends_on:
      - redis1
      - redis2
    networks:
      - kafka_network

  redis1:
    image: redis:6
    container_name: redis-primary
    ports:
      - "6379:6379"
    networks:
      - kafka_network

  redis2:
    image: redis:6
    container_name: redis-secondary
    ports:
      - "6380:6379"
    networks:
      - kafka_network

networks:
  kafka_network:
    external: true
